### ISSUE TITLE
Synchonisation / Restore from other instance partially broken

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/zou#677]
**Context**

Studio name: 
Zou version: 0.17.18
Zou installation type: self-hosted

**Describe the bug**
synching between two instances fails using:

. /opt/zou/zouenv/bin/activate
DB_PASSWORD=DBPASSWORD SYNC_LOGIN="me@me.com" SYNC_PASSWORD="DBPASSWORD" zou sync-full --target http://192.168.1.68/api --project MY-PROJECT-TO-COPY-ACROSS

Resulting in:

Start syncing.
2023-08-02 14:35:01,827 - INFO - 62 persons synced.
2023-08-02 14:35:01,849 - INFO - 1 organisations synced.
2023-08-02 14:35:01,904 - INFO - 2 project-status synced.
2023-08-02 14:35:01,955 - INFO - 7 departments synced.
2023-08-02 14:35:02,112 - INFO - 30 task-types synced.
2023-08-02 14:35:02,175 - INFO - 8 task-status synced.
2023-08-02 14:35:02,198 - INFO - 0 custom-actions synced.
2023-08-02 14:35:02,383 - INFO - 30 entity-types synced.
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/cli.py", line 277, in sync_full
    commands.import_data_from_another_instance(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/utils/commands.py", line 407, in import_data_from_another_instance
    sync_service.run_main_data_sync(project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 243, in run_main_data_sync
    sync_entries(path, model, project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 362, in sync_entries
    instances = [gazu.client.fetch_one(model_name, project.get("id"))]
AttributeError: 'NoneType' object has no attribute 'get'

Both kitsu / zou instances are running the same version.

**Comment by PeteDraper** [comment]
Still broken - to confirm cloned the entire instance, added a new project with entires and attempted the sync. Result:

Start syncing.
2023-09-02 07:17:51,481 - INFO - 60 persons synced.
2023-09-02 07:17:51,506 - INFO - 1 organisations synced.
2023-09-02 07:17:51,549 - INFO - 2 project-status synced.
2023-09-02 07:17:51,616 - INFO - 7 departments synced.
2023-09-02 07:17:51,779 - INFO - 31 task-types synced.
2023-09-02 07:17:51,856 - INFO - 10 task-status synced.
2023-09-02 07:17:51,886 - INFO - 0 custom-actions synced.
2023-09-02 07:17:52,049 - INFO - 31 entity-types synced.
2023-09-02 07:17:52,157 - INFO - 1 projects synced.
2023-09-02 07:17:52,175 - INFO - Syncing PROJECTNAME...
2023-09-02 07:17:52,176 - INFO - Syncing episodes...
2023-09-02 07:17:52,231 - INFO -     1 episodes synced.
2023-09-02 07:17:52,231 - INFO - Syncing sequences...
2023-09-02 07:17:52,273 - INFO -     1 sequences synced.
2023-09-02 07:17:52,273 - INFO - Syncing assets...
2023-09-02 07:17:52,308 - INFO -     1 assets synced.
2023-09-02 07:17:52,308 - INFO - Syncing shots...
2023-09-02 07:17:52,451 - INFO -     7 shots synced.
2023-09-02 07:17:52,451 - INFO - Syncing tasks...
2023-09-02 07:17:53,399 - INFO -     46 tasks synced.
2023-09-02 07:17:53,399 - INFO - Syncing preview-files...
2023-09-02 07:17:53,642 - INFO -     29 preview-files synced.
2023-09-02 07:17:53,643 - INFO - Syncing time-spents...
2023-09-02 07:17:53,663 - INFO -     0 time-spents synced.
2023-09-02 07:17:53,663 - INFO - Syncing playlists...
2023-09-02 07:17:53,679 - INFO -     0 playlists synced.
2023-09-02 07:17:53,679 - INFO - Syncing build-jobs...
2023-09-02 07:17:53,694 - INFO -     0 build-jobs synced.
2023-09-02 07:17:53,694 - INFO - Syncing comments...
2023-09-02 07:18:00,328 - INFO -     164 comments synced.
2023-09-02 07:18:00,328 - INFO - Syncing attachment-files...
2023-09-02 07:18:00,357 - INFO -     1 attachment-files synced.
2023-09-02 07:18:00,358 - INFO - Syncing metadata-descriptors...
2023-09-02 07:18:00,375 - INFO -     0 metadata-descriptors synced.
2023-09-02 07:18:00,376 - INFO - Syncing schedule-items...
2023-09-02 07:18:00,390 - INFO -     0 schedule-items synced.
2023-09-02 07:18:00,390 - INFO - Syncing subscriptions...
2023-09-02 07:18:00,411 - INFO -     0 subscriptions synced.
2023-09-02 07:18:00,411 - INFO - Syncing notifications...
2023-09-02 07:18:01,081 - INFO -     191 notifications synced.
2023-09-02 07:18:01,081 - INFO - Syncing entity-links...
2023-09-02 07:18:01,102 - INFO -     0 entity-links synced.
2023-09-02 07:18:01,102 - INFO - Syncing newss...
2023-09-02 07:18:02,326 - INFO -     164 news synced.
2023-09-02 07:18:02,326 - INFO - Syncing milestones...
2023-09-02 07:18:02,345 - INFO -     0 milestones synced.
2023-09-02 07:18:02,366 - INFO -     0 assets thumbnails synced.
2023-09-02 07:18:02,418 - INFO -     7 shots thumbnails synced.
2023-09-02 07:18:02,418 - INFO - Sync of PROJECTNAME complete.
2023-09-02 07:18:02,455 - INFO - 0 search-filters synced.
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/cli.py", line 280, in sync_full
    commands.import_data_from_another_instance(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/utils/commands.py", line 465, in import_data_from_another_instance
    sync_service.run_other_sync(project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 271, in run_other_sync
    sync_entries("day-offs", SearchFilter, project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 369, in sync_entries
    model.create_from_import_list(instances)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 150, in create_from_import_list
    cls.create_from_import(data)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 136, in create_from_import
    return cls.create(**data)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 85, in create
    instance = cls(**kw)
  File "<string>", line 4, in __init__
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 567, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 2134, in _declarative_constructor
    raise TypeError(
TypeError: 'date' is an invalid keyword argument for SearchFilter

**Comment by EvanBldy** [comment]
Hi @PeteDraper,
Thanks for the report.
I should be fixed in Zou 0.17.42. 
Can you close if it's good for you ?

**Comment by PeteDraper** [comment]
Still getting errors - this time different from before. Both instances using same Zou 0.17.43 and upgraded to latest Kitsu 0.17.33:

(zouenv) kitsu@kitsu:/$ DB_PASSWORD=DBPASSWORD SYNC_LOGIN="me@me.com" SYNC_PASSWORD="KITSUPASSWORD" zou sync-full --target http://192.168.1.61/api --project MYPROJECT
Start syncing.
2023-10-13 10:47:01,510 - INFO - 61 persons synced.
2023-10-13 10:47:01,530 - INFO - 1 organisations synced.
2023-10-13 10:47:01,569 - INFO - 2 project-status synced.
2023-10-13 10:47:01,628 - INFO - 7 departments synced.
2023-10-13 10:47:01,806 - INFO - 31 task-types synced.
2023-10-13 10:47:01,885 - INFO - 10 task-status synced.
2023-10-13 10:47:01,909 - INFO - 0 custom-actions synced.
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "ix_entity_type_name"
DETAIL:  Key (name)=(COSMETICS) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/cli.py", line 281, in sync_full
    commands.import_data_from_another_instance(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/utils/commands.py", line 463, in import_data_from_another_instance
    sync_service.run_main_data_sync(project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 246, in run_main_data_sync
    sync_entries(path, model, project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 373, in sync_entries
    model.create_from_import_list(instances)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 150, in create_from_import_list
    cls.create_from_import(data)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/entity_type.py", line 47, in create_from_import
    entity_type.update(data)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 211, in update
    db.session.commit()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 554, in commit
    return self._proxied.commit()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4315, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.IntegrityError: (psycopg.errors.UniqueViolation) duplicate key value violates unique constraint "ix_entity_type_name"
DETAIL:  Key (name)=(COSMETICS) already exists.
[SQL: UPDATE entity_type SET name=%(name)s::VARCHAR, id=%(id)s::UUID, created_at=%(created_at)s::TIMESTAMP WITHOUT TIME ZONE, updated_at=%(updated_at)s::TIMESTAMP WITHOUT TIME ZONE WHERE entity_type.id = %(entity_type_id)s::UUID]
[parameters: {'name': 'COSMETICS', 'id': '22c3faca-99ed-46fa-a926-d4d61526da25', 'created_at': '2022-10-24T13:26:01', 'updated_at': '2023-09-21T07:47:10', 'entity_type_id': '22c3faca-99ed-46fa-a926-d4d61526da25'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
(zouenv) kitsu@kitsu:/$

**Comment by EvanBldy** [comment]
Can you clear the DB of the synced one ?

**Comment by PeteDraper** [comment]
Cleared the DB of the instance I wanted to copy to using 
zou clear-db
zou reset-migrations
zou upgrade-db

got these errors when trying to sync the single project again. Note: it created the project but did not produce the episode structure and when trying to select the shots it just sits and hangs in Kitsu.

Start syncing.
2023-10-13 14:11:37,239 - INFO - 61 persons synced.
2023-10-13 14:11:37,259 - INFO - 1 organisations synced.
2023-10-13 14:11:37,295 - INFO - 2 project-status synced.
2023-10-13 14:11:37,348 - INFO - 7 departments synced.
2023-10-13 14:11:37,524 - INFO - 31 task-types synced.
2023-10-13 14:11:37,641 - INFO - 10 task-status synced.
2023-10-13 14:11:37,665 - INFO - 0 custom-actions synced.
2023-10-13 14:11:37,854 - INFO - 35 entity-types synced.
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.ForeignKeyViolation: insert or update on table "project_status_automation_link" violates foreign key constraint "project_status_automation_link_status_automation_id_fkey"
DETAIL:  Key (status_automation_id)=(d7d06a15-9991-443b-b9cf-a544aa8c77db) is not present in table "status_automation".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/cli.py", line 281, in sync_full
    commands.import_data_from_another_instance(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/utils/commands.py", line 463, in import_data_from_another_instance
    sync_service.run_main_data_sync(project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 246, in run_main_data_sync
    sync_entries(path, model, project=project)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/sync_service.py", line 373, in sync_entries
    model.create_from_import_list(instances)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 150, in create_from_import_list
    cls.create_from_import(data)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/project.py", line 207, in create_from_import
    previous_project.set_status_automations(status_automation_ids)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/project.py", line 166, in set_status_automations
    return self.set_links(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 229, in set_links
    link = LinkTable.query.filter_by(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2743, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2123, in _execute_internal
    ) = compile_state_cls.orm_pre_session_exec(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 551, in orm_pre_session_exec
    session._autoflush()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2939, in _autoflush
    raise e.with_traceback(sys.exc_info()[2])
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2928, in _autoflush
    self.flush()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4315, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg.errors.ForeignKeyViolation) insert or update on table "project_status_automation_link" violates foreign key constraint "project_status_automation_link_status_automation_id_fkey"
DETAIL:  Key (status_automation_id)=(d7d06a15-9991-443b-b9cf-a544aa8c77db) is not present in table "status_automation".
[SQL: INSERT INTO project_status_automation_link (project_id, status_automation_id) VALUES (%(project_id)s::UUID, %(status_automation_id)s::UUID)]
[parameters: {'project_id': '203c4a0b-3e71-4f64-8534-713a63c844cd', 'status_automation_id': 'd7d06a15-9991-443b-b9cf-a544aa8c77db'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

**Comment by jeremy-bepoix** [comment]
Hi i ran the same issue, docs is not up to date with the latest release. `--target` args won't work but `--source` does.
What i can see on zou/cli.py
```
root@7ffcd552c911:/usr/local/lib/python3.11/site-packages/zou# zou sync-full --help
Usage: zou sync-full [OPTIONS]

  Retrieve all data from source instance. It expects that credentials to
  connect to source instance are given through SYNC_LOGIN and SYNC_PASSWORD
  environment variables.

Options:
  --source TEXT
  --project TEXT
  --no-projects
  --with-events
  --only-projects
  --help           Show this message and exit.
```
https://github.com/cgwire/zou/blob/master/zou/cli.py#L283-L313

So it should be : 
```
export SYNC_LOGIN="admin@example.com"
export SYNC_PASSWORD="mysecretpassword"
zou sync-full --source https://old-kitsu-instance/api --project project_name
```
And it work, but so many errors with duplicate key value, and its normal. Possible to add another flag (e.g : skip-existing) ?
regards,

**Comment by jeremy-bepoix** [comment]
So to avoid issue i reforced to clear database
```
zou clear-db
zou reset-migrations
zou upgrade-db
```
then run : 
```zou sync-full --source https://old-kitsu-instance/api --project project_name```

if needed, i'll test with kitsu 0.15.7, 0.16.5, 0.17.15 >> 0.19.7

And on latest one : 0.15.7 >> 0.19.7
```
Start syncing.
2024-03-05 15:19:08,201 - INFO - 33 persons synced.
2024-03-05 15:19:08,222 - INFO - 1 organisations synced.
2024-03-05 15:19:08,265 - INFO - 2 project-status synced.
2024-03-05 15:19:08,370 - INFO - 13 departments synced.
2024-03-05 15:19:08,660 - INFO - 42 task-types synced.
2024-03-05 15:19:08,756 - INFO - 12 task-status synced.
2024-03-05 15:19:08,786 - INFO - 0 custom-actions synced.
2024-03-05 15:19:08,935 - INFO - 19 entity-types synced.
2024-03-05 15:19:09,084 - INFO - 1 projects synced.
2024-03-05 15:19:09,100 - INFO - Syncing Guercoeur...
2024-03-05 15:19:09,100 - INFO - Syncing episodes...
2024-03-05 15:19:09,118 - INFO -     0 episodes synced.
2024-03-05 15:19:09,118 - INFO - Syncing sequences...
2024-03-05 15:19:09,169 - INFO -     1 sequences synced.
2024-03-05 15:19:09,169 - INFO - Syncing assets...
2024-03-05 15:19:10,162 - INFO -     52 assets synced.
2024-03-05 15:19:10,163 - INFO - Syncing shots...
2024-03-05 15:19:10,240 - INFO -     3 shots synced.
2024-03-05 15:19:10,240 - INFO - Syncing tasks...
2024-03-05 15:19:17,528 - INFO -     324 tasks synced.
2024-03-05 15:19:17,529 - INFO - Syncing preview-files...
2024-03-05 15:19:18,540 - INFO -     152 preview-files synced.
2024-03-05 15:19:18,541 - INFO - Syncing time-spents...
2024-03-05 15:19:18,674 - INFO -     17 time-spents synced.
2024-03-05 15:19:18,674 - INFO - Syncing playlists...
2024-03-05 15:19:18,725 - INFO -     2 playlists synced.
2024-03-05 15:19:18,725 - INFO - Syncing build-jobs...
2024-03-05 15:19:18,743 - INFO -     0 build-jobs synced.
2024-03-05 15:19:18,743 - INFO - Syncing comments...
2024-03-05 15:19:26,239 - INFO -     160 comments synced.
2024-03-05 15:19:26,239 - INFO - Syncing concepts...
Traceback (most recent call last):
  File "/usr/local/bin/zou", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zou/cli.py", line 304, in sync_full
    commands.import_data_from_another_instance(
  File "/usr/local/lib/python3.11/site-packages/zou/app/utils/commands.py", line 493, in import_data_from_another_instance
    sync_service.run_project_data_sync(project=project)
  File "/usr/local/lib/python3.11/site-packages/zou/app/services/sync_service.py", line 304, in run_project_data_sync
    sync_project_entries(project, path, model)
  File "/usr/local/lib/python3.11/site-packages/zou/app/services/sync_service.py", line 458, in sync_project_entries
    results = gazu.client.fetch_all(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gazu/client.py", line 339, in fetch_all
    return get(url_path_join("data", path), params=params, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gazu/client.py", line 206, in get
    check_status(response, path)
  File "/usr/local/lib/python3.11/site-packages/gazu/client.py", line 298, in check_status
    raise RouteNotFoundException(path)
gazu.exception.RouteNotFoundException: data/projects/f836afc9-fc9a-4cee-9d48-b199ffb9b1e2/concepts
```

**Comment by frankrousseau** [comment]
Ping @EvanBldy

**Comment by EvanBldy** [comment]
I have fixed all the issues that I was able to reproduce. Can you retry? 
I close this issue, for now, if your problems persist can you reopen or do a new issue ?
Thanks
